proyectoDanerSa/Apps/clientes/urls.py
from django.urls import path

from . import views

app_name = "Apps.clientes"
urlpatterns = [
    path('', views.ListaClientesView, name='lista_clientes'),
    path('agregar', views.VistaAgregarCliente, name='agregar_cliente'),
    path('actualizar/<str:id_cliente>/',
        views.VistaActulizarCliente, name='actualizar_cliente'),
    path('eliminar/<str:id_cliente>/',
        views.VistaEliminarCliente, name='eliminar_cliente'),
    path('detalles/<str:id_cliente>/',
        views.DetalleClientesView, name='detalles_clientes'),
    path("get", views.GetClientsAJAXView, name="get_clientes"),




    path('report', views.VistaCliente, name='VistaCliente'),
]

proyectoDanerSa/proyectoDanerSa/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.urls import include, path
from Apps.pos.views import ListaVentasgraph  # Importa la vista desde el espacio de nombres "Apps.pos"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Apps.pos.urls')),
    path('', include('Apps.authentication.urls')),
    path('inventario/', include('Apps.inventario.urls')),
    path('clientes/', include('Apps.clientes.urls')),
    path('ventas/', include('Apps.ventas.urls')),
    path('compras/', include('Apps.compras.urls')),
    path('rutas/', include('Apps.rutas.urls')),
    path('reporte_generales/', include('Apps.reportes_generales.urls')),
]

proyectoDanerSa/Apps/clientes/models.py
from django.db import models
from decimal import Decimal
from Apps.rutas.models import Ruta
class Cliente(models.Model):

    nombre = models.CharField(max_length=256)
    direccion = models.TextField(max_length=256, blank=False, null=False)
    telefono = models.CharField(max_length=30, blank=False, null=False)
    saldo = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'), blank=False, null=True)
    activo = models.BooleanField(default=True, blank=False, null=True)
    ruta = models.ForeignKey(Ruta, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'clientes'
    
    def to_json(self):
        return {
            'id': self.id,
            'nombre': self.nombre,
            'saldo': self.saldo,
        }

proyectoDanerSa/Apps/ventas/models.py
from django.db import models
from Apps.clientes.models import Cliente
from Apps.inventario.models import Producto
from django.utils import timezone
from django.db.models import Sum 
from django.contrib.auth.models import User

class Venta(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    fecha = models.DateField(default=timezone.now)
    id_clientes = models.ForeignKey(
        Cliente, models.DO_NOTHING, db_column='id_clientes')
    total = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    anticipo = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    estado_cuenta = models.BooleanField(default=True)
    comentario = models.CharField(max_length=256, blank=True, null=True)

    class Meta:
        db_table = 'Venta'
    
    def getSaldo(self):
        saldo = self.total - self.anticipo
        return saldo
    
    def get_suma_abonos(self):
        abonos_total = self.transacciones_venta.aggregate(Sum('abono'))['abono__sum']
        return abonos_total or 0

class DetalleVenta(models.Model):
    id_venta = models.ForeignKey(
        Venta, models.DO_NOTHING, db_column='venta')
    id_producto = models.ForeignKey(
        Producto, models.DO_NOTHING, db_column='producto')
    precio = models.DecimalField(max_digits=15, decimal_places=2)
    ganancia = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    cantidad = models.IntegerField()

    class Meta:
        db_table = 'DetalleVenta'

    def getprecioCompraActual(self):
        precio_compra = self.precio - self.ganancia
        return precio_compra




class Transaccion(models.Model):
    fecha = models.DateField(default=timezone.now)
    id_cliente = models.ForeignKey(Cliente, models.DO_NOTHING, db_column='cliente')
    id_venta = models.ForeignKey(Venta, models.DO_NOTHING, related_name='transacciones_venta')
    abono = models.DecimalField(max_digits=15, decimal_places=2)
    saldo_venta = models.DecimalField(max_digits=15, decimal_places=2)
    saldo_cliente = models.DecimalField(max_digits=15, decimal_places=2)

    class Meta:
        db_table = 'Transaccion'

proyectoDanerSa/Apps/clientes/forms.py
from django import forms
from .models import Cliente

class ClienteienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre', 'saldo']

proyectoDanerSa/Apps/clientes/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Cliente
from Apps.ventas.models import Venta, Transaccion
from Apps.rutas.models import Ruta
from django.contrib import messages
from django.db.models import Sum
from django.http import JsonResponse
from django.views import View
from django.db.models import Q

@login_required(login_url="/accounts/login/")
def ListaClientesView(request):
    context = {
        "clientes": Cliente.objects.filter(activo=True).exclude(id=1),
        "rutas": Ruta.objects.filter(activo=True),
    }
    return render(request, "clientes/clientes.html", context=context)



        
@login_required(login_url="/accounts/login/")
def DetalleClientesView(request, id_cliente):
    cliente = Cliente.objects.get(pk=id_cliente)

    ventas_no_pagadas = Venta.objects.filter(id_clientes=id_cliente, estado_cuenta=True)
    transaccion = Transaccion.objects.all()
    ()

    for venta in ventas_no_pagadas:
        venta.saldo = venta.getSaldo()

    context = {
        "cliente": cliente,
        "ventas": ventas_no_pagadas,
    }
    return render(request, "clientes/detalles_cliente.html", context=context)


@login_required(login_url="/accounts/login/")
def VistaAgregarCliente(request):
    context={
        "rutas": Ruta.objects.filter(activo=True),
    }
    if request.method == 'POST':
        data = request.POST
        attributes = {
            "nombre": data['nombre'],
            "direccion": data['direccion'],
            "telefono": data['telefono'],
        }
        ruta_id = data['ruta_select']
        ruta_instance = Ruta.objects.get(id=ruta_id)
        attributes["ruta"] = ruta_instance
        if Cliente.objects.filter(**attributes).exists():
            messages.error(request, '¡El cliente ya existe!',
                extra_tags="warning")
            return redirect('Apps.clientes:agregar_cliente')
        try:
            new_customer = Cliente.objects.create(**attributes)
            new_customer.save()
            messages.success(request, '¡Cliente: ' + attributes["nombre"] + " " + ' Creado con éxito!', extra_tags="success")
            return redirect('Apps.clientes:lista_clientes')
        except Exception as e:
            messages.success(request, f'Error en cliente: {str(e)}', extra_tags="danger")
            
            return redirect('Apps.clientes:agregar_cliente')
    return render(request, "clientes/agregar_clientes.html",context=context)


@login_required(login_url="/accounts/login/")
def VistaActulizarCliente(request, id_cliente):
    try:
        cliente = Cliente.objects.get(id=id_cliente)
    except Exception as e:
        messages.success(
            request, '¡Hubo un error al intentar localizar al cliente!', extra_tags="danger")
        return redirect('Apps.clientes:lista_clientes')
    context = {
        "cliente": cliente,
    }
    if request.method == 'POST':
        try:
            data = request.POST
            attributes = {
                "nombre": data['nombre'],
                "direccion": data['direccion'],
                "telefono": data['telefono'],
            }
            ruta_id = data['ruta_select']
            ruta_instance = Ruta.objects.get(id=ruta_id)
            attributes["ruta"] = ruta_instance
            cliente = Cliente.objects.filter(
                id=id_cliente).update(**attributes)
            cliente = Cliente.objects.get(id=id_cliente)
            messages.success(request, '¡Cliente: ' + cliente.nombre +
                ' actualizado exitosamente!', extra_tags="success")
            return redirect('Apps.clientes:lista_clientes')
        except Exception as e:
            messages.success(
                request, '¡Hubo un error durante la actualización!', extra_tags="danger")
            return redirect('Apps.clientes:lista_clientes')
    return render(request, "clientes/actualizar_ clientes.html", context=context)


@login_required(login_url="/accounts/login/")
def VistaEliminarCliente(request, id_cliente):
    try:
        cliente = Cliente.objects.get(id=id_cliente)
        cliente.activo = False
        cliente.save()
        messages.success(request, '¡Cliente: ' + cliente.nombre +
            ' Eliminado!', extra_tags="success")
        return redirect('Apps.clientes:lista_clientes')
    except Exception as e:
        messages.success(
            request, '¡Hubo un error durante la eliminación!', extra_tags="danger")
        return redirect('Apps.clientes:lista_clientes')
    
def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

def GetClientsAJAXView(request):
    if request.method == 'POST':
        if is_ajax(request=request):
            data = []
            clientes = Cliente.objects.filter(nombre__icontains=request.POST['term'],activo=True)
            for cliente in clientes[0:10]:
                item = cliente.to_json()
                data.append(item)

            return JsonResponse(data, safe=False)
        


#para reportes---------------
def VistaCliente(request):
    clientes = Cliente.objects.filter(activo=True)
    print(clientes)  # Añadir esta línea para imprimir los clientes en la consola
    context = {
        "clientes": clientes,
    }

    return render(request, "ventas/Vreport.html", context=context)

proyectoDanerSa/templates/clientes/agregar_clientes.html
{% extends "pos/base.html" %}
{% load static %}
{% block title %}Agregar cliente{% endblock title %}

{% block stylesheets %}
{% endblock stylesheets %}

{% block heading %}Crear cliente{% endblock heading %}

{% block content %}

<div class="row ml-0 mb-3">
    <a href="{% url 'Apps.clientes:lista_clientes' %}">
        <button type="button" class="btn m-2 m-sm-3 btn-back">
            <i class="fas fa-long-arrow-alt-left mr-2"></i>
            Volver
        </button>
    </a>
</div>


<div class="row row-font-family">
    <div class="card col-md-8">
        <div class="card-body">
            <form action="{% url 'Apps.clientes:agregar_cliente' %}"  method="post" id="formcliente">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="inputDescription">Nombre</label>
                        <input type="text" class="form-control" name="nombre" placeholder="Juan..." required>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="inputDescription">Telefono</label>
                        <input type="text" name="telefono" class="form-control" placeholder="72752736" pattern="\d{8}" maxlength="8" title="Ingrese exactamente 8 dígitos" required>
                        <small id="telefonoHelp" class="form-text text-muted">Ingrese un número de teléfono válido (exactamente 8 dígitos).</small>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label for="inputDescription">Direccion</label>
                        <textarea name="direccion" class="form-control" placeholder="3ra calle 5-9 san mateo, Quet.." rows="2" required></textarea>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="ruta_select">Selecciona una Ruta:</label>
                        <select name="ruta_select" id="ruta_select" class="form-control">
                            {% for ruta in rutas %}
                                <option value="{{ ruta.id }}">{{ ruta.nombre_ruta}} - {{ ruta.descripcion_ruta }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <button type="submit" class="btn btn-accept">Crear cliente</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}
{% block javascripts %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
document.getElementById('formcliente').addEventListener('submit', function (event) {
    var telefonoInput = document.getElementsByName('telefono')[0];
    var saldoInput = document.getElementsByName('saldo')[0];
    var rutaSelect = document.getElementById('ruta_select');
    
    if (!/^\d{8}$/.test(telefonoInput.value)) {
        Swal.fire({
            title: 'Advertencia',
            text: 'El número de teléfono debe contener exactamente 8 dígitos.',
            icon: 'warning',
            customClass: {
                    popup: 'my-swal-center',
                },
        });
        event.preventDefault();
    }

    var saldoValue = parseFloat(saldoInput.value);
    if (isNaN(saldoValue) || saldoValue < 0) {
        Swal.fire({
            title: 'Advertencia',
            text: 'Ingrese un saldo válido.',
            icon: 'warning',
            customClass: {
                    popup: 'my-swal-center',
                },
        });
        event.preventDefault();
    }
    if (rutaSelect.value === '') {
        Swal.fire({
            title: 'Advertencia',
            text: 'Por favor, selecciona una ruta.',
            icon: 'warning',
            customClass: {
                popup: 'my-swal-center',
            },
        });
        event.preventDefault();
        return;
    }
});
</script>
{% endblock javascripts %}

proyectoDanerSa/templates/clientes/detalles_cliente.html
{% extends "pos/base.html" %}
{% load static %}
{% block title %}Detalles de cliente{% endblock title %}

{% block stylesheets %}
{% endblock stylesheets %}

{% block heading %}Detalles de cliente{% endblock heading %}

{% block content %}

<div class="row ml-0 mb-3">
    <a href="{% url 'Apps.clientes:lista_clientes' %}">
        <button type="button" class="btn m-2 m-sm-3 btn-back">
            <i class="fas fa-long-arrow-alt-left mr-2"></i>
            Volver
        </button>
    </a>
</div>


<div class="row row-font-family">
    <div class="card col-md-8">
        <div class="card-body">
                <div class="form-row" id="name_cliente_div" style="text-align: center;">
                    <div class="form-group col-md-3" style="text-align: center;">
                        <label id="name_cliente">{{cliente.nombre}}</label>
                    </div>
                </div>
                <div class="form-row" id="informacion_cliente">
                    <div class="form-group col-md-3">
                        <label for="inputDescription" style="margin-right: 5px;"> Telefono:</label>
                        <input type="text" name="telefono" class=" input_cliente" value="{{cliente.telefono}}" readonly>
                    </div>
                    <div class="form-group col-md-6" style="display: flex; align-items: self-start;" >
                        <label for="inputDescription" style="margin-right: 5px;">Direccion:</label>
                        <textarea name="direccion" class=" input_cliente" rows="1"  readonly>{{cliente.direccion}}</textarea>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="ruta" style="margin-right: 5px;"> Ruta:</label>
                        <input type="text" name="ruta" class=" input_cliente" value="{{cliente.ruta.nombre_ruta}}" readonly>
                    </div>
                    <div class="form-group col-md-3 input_saldo">
                        <label for="inputDescription" style="margin-right: 5px;">Saldo:</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text input_cliente">
                                    <i class="fab fa-quora quora-icon quora-icon-{{ v.id }}" style="font-size: 20px; color: rgb(197, 6, 6)"></i>
                                </span>
                            </div>
                            <input type="text" class="input_cliente abono-input abono-input-{{ v.id }}" name="saldo" value="{{ cliente.saldo }}" style="color: rgb(197, 6, 6)" required>
                        </div>
                    </div>
                </div>
                <div>
                    <label for="inputDescription" style="margin-right: 5px;">Ventas Pendientes:</label>
                <div class="table-container">
                    <table class="table1 table  table-hover mx-auto id_table_detalle" id="dataTable">
                        <thead>
                            <tr>
                                <th class="d-none d-sm-table-cell">ID</th>
                                <th class="d-none d-sm-table-cell" style="width:5%">#</th>
                                <th style="width:15%">Total</th>
                                <th class="d-none d-sm-table-cell" style="width:15%">Anticipo</th>
                                <th style="width:15%">Saldo</th>
                                <th style="width:15%">Fecha</th>
                                <th class="text-center" style="width:15%">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for v in ventas %}
                            <tr>
                                <td class="d-none d-sm-table-cell">{{v.id}}</td>
                                <td class="d-none d-sm-table-cell">{{forloop.counter}}</td>
                                <td>{{v.total}}</td>
                                <td class="d-none d-sm-table-cell">{{v.anticipo}}</td>
                                <td>{{v.getSaldo}}</td>
                                <td>{{v.fecha}}</td>
                                <td class="text-center">
                                    <a class="text-decoration-none" data-toggle="modal" data-target="#DetalleVentas-clientes{{ v.id }}">
                                        <button rel="ver" type="button" class="btn btn-info btn-sm">
                                            <i class="fas fa-eye"></i>
                                        </button>
                                    </a>
                                </td>
                                
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                </div>
        </div>
    </div>
</div>
{% for v in ventas %}
<div class="modal fade" id="DetalleVentas-clientes{{ v.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel-cliente" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                
                <h5 class="modal-title" id="exampleModalLabel-cliente">Detalles de Venta</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{% url 'Apps.ventas:agregar_abono' v.id %}"  method="post" id="form-detallecliente">
                {% csrf_token %}
            <div class="modal-body">
                <p><b>Fecha:</b> {{ v.fecha }}</p>
                <h6><b>Productos Vendidos:</b></h6>
                {% if v.detalleventa_set.all %}
                    <ul>
                        {% for detalle in v.detalleventa_set.all %}
                            <li>{{ detalle.cantidad }} x {{ detalle.id_producto.nombre }} - Precio: {{ detalle.precio }}</li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>No hay detalles de productos vendidos.</p>
                {% endif %}
                <p><b>Comentario:</b> {{v.comentario}}</p>
                <p><b>Total:</b> {{ v.total }}</p>
                <p><b>Anticipo:</b> {{ v.anticipo }}</p>
                <p><b>Saldo:</b> <span id="saldoSpan">{{ v.getSaldo }}</span></p>
                <hr>
                {% if v.transacciones_venta.last %}
                {% if v.transacciones_venta.last.saldo_venta %}
                    <p><b>Abonos:</b></p>
                    <table class="table1 table table-hover mx-auto id_table_detalle">
                        <thead>
                            <tr>
                                <th>Fecha de Abono</th>
                                <th>Abono</th>
                                <th>Saldo de Venta</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for transaccion in v.transacciones_venta.all %}
                                <tr>
                                    <td>{{ transaccion.fecha }}</td>
                                    <td>{{ transaccion.abono }}</td>
                                    <td>{{ transaccion.saldo_venta }}</td>
                                </tr>
                            {% endfor %}
                            <tr>
                                <td><b class="total-abonos">Total Abonos:</b></td>
                                <td><b class="total-abonos">{{ v.get_suma_abonos }}</b></td>
                                <td><b class="saldo-actual">Saldo Actual: {{ v.transacciones_venta.last.saldo_venta }}</b></td>
                            </tr>                            
                        </tbody>
                    </table>
            
                    <p><b>Pendiente:</b> <span class="pendientes_id">{{ v.transacciones_venta.last.saldo_venta }}</span></p>
                {% else %}
                    <p><b>Abonos: No hay abonos</b></p>
                    <p><b>{{ v.getSaldo }}</b></p>
                {% endif %}
            {% else %}
                <p><b>Pendientes:</b> <span class="pendientes_id">{{ v.getSaldo }}</span></p>
                <p><b>Abonos: No existen abonos</b></p>
            {% endif %}           
            </div>
                <div class="form-group col-md-6">
                    <label for="abono"><strong>Abono:</strong></label>
                    <div class="contiener-product-fas">
                        <div class="col-md-2 relleno relleno_detalles" ><i class="fab fa-quora" ></i></div>
                        <div class="col-md-6 abono_input">
                            <input type="text" name="abono" class="form-control"  style="background-color: #ccffcc;" required>
                        </div>
                    </div>
                </div>
                <div style="text-align: center; margin-bottom: 3%;">
                    <button type="submit" class="btn btn-accept">Abonar</button>
                </div>
            </form>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock content %}
{% block javascripts %}
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.6.15/dist/sweetalert2.all.min.js"></script>
<script>
$(document).ready(function() {
    
    $('input[name="abono"]').on('input', function() {
        validarAbono(this);
    });

    
    var quoraIcon = document.querySelector(".quora-icon-{{ v.id }}");
    var abonoInput = document.querySelector(".abono-input-{{ v.id }}");
    var saldo = parseFloat("{{ cliente.saldo }}");

    if (saldo === 0) {
        quoraIcon.style.color = "green";
        abonoInput.style.color= "green"; // Cambia el fondo del campo de abono
    } else if (saldo >= 1 && saldo <= 50) {
        quoraIcon.style.color = "#ffd700";
        abonoInput.style.color= "#ffd700"; // Cambia el fondo del campo de abono
    } else {
        quoraIcon.style.color = "red";
        abonoInput.style.color= "red"; // Cambia el fondo del campo de abono
    }
});


function validarAbono(inputElement) {
    var pendienteId = parseFloat($(inputElement).closest('.modal').find('.pendientes_id').text()) || 0;
    var abono = parseFloat($(inputElement).closest('.modal').find('input[name="abono"]').val()) || 0;

    if (abono < 0) {
        Swal.fire({
            title: 'Advertencia',
            text: 'El abono no puede ser menor o igual a 0',
            icon: 'warning',
            customClass: {
                popup: 'my-swal-center',
            },
        });
        $('input[name="abono"]').val('1');
    }

    if (abono > pendienteId) {
        Swal.fire({
            title: 'Advertencia',
            text: 'El abono no puede ser mayor al saldo pendiente',
            icon: 'warning',
            customClass: {
                popup: 'my-swal-center',
            },
        });
        $('input[name="abono"]').val(pendienteId);
    }
}


</script>
<script>
$(document).ready(function() {
    
    document.getElementById('form-detallecliente').addEventListener('submit', function (event) {
        var saldoInput = document.getElementsByName('abono')[0];

        var saldoValue = parseFloat(saldoInput.value);
        if (saldoValue <= 0) {
            Swal.fire({
                title: 'Advertencia',
                text: 'No le es posible efectuar un abono de valor "0"',
                icon: 'warning',
                customClass: {
                    popup: 'my-swal-center',
                },
            });
            event.preventDefault();
        }
    });
});
</script>
{% endblock javascripts %}